CREATE TABLE market_calendar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country VARCHAR(2) NOT NULL,
    date DATE NOT NULL,
    status VARCHAR(20) NOT NULL,
    integrated JSONB,
    CONSTRAINT uk_market_calendar_country_date UNIQUE (country, date)
);
