services:
  market-monitor-renderer:
    image: ghcr.io/fwangchanju/market-monitor-renderer:latest
    container_name: market-monitor-renderer
    restart: always
    environment:
      - CAPTURE_URL=${CAPTURE_URL}
      - CAPTURE_USER=${CAPTURE_USER}
      - CAPTURE_PASS=${CAPTURE_PASS}
    ports:
      - "3000:3000"
    shm_size: '128m'
