services:
  market-monitor-renderer:
    image: ghcr.io/fwangchanju/market-monitor-renderer:latest
    container_name: market-monitor-renderer
    restart: always
    env_file:
      - ${HOME}/env/market-monitor.env
    ports:
      - "3000:3000"
    shm_size: '128m'
