spring.application.name=market-monitor

spring.datasource.url=jdbc:postgresql://localhost:5433/market_monitor_db
spring.datasource.username=market_monitor
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

kiwoom.app-key=${KIWOOM_APP_KEY_B}
kiwoom.secret=${KIWOOM_SECRET_B}

krx.login-id=${KRX_ID}
krx.login-pw=${KRX_PW}
dashboard.base-url=http://localhost:8081
telegram.bot-token=${TELEGRAM_BOT_TOKEN}
telegram.chat-id=${TELEGRAM_CHAT_ID}
telegram.developer-chat-id=${DEVELOPER_CHAT_ID}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:flyway
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

krx.enabled=false

server.port=8081
server.servlet.context-path=/market-monitor
server.forward-headers-strategy=framework
