krx.enabled=false

renderer.url=${RENDERER_URL:http://market-monitor-renderer:3000}

dashboard.base-url=https://eolmae.duckdns.org

krx.login-id=${KRX_ID}
krx.login-pw=${KRX_PW}

spring.datasource.url=${DB_URL:jdbc:postgresql://market-monitor-postgres:5433/market_monitor_db}
spring.datasource.password=${DB_PASSWORD}
